### ISSUE TITLE
Error: [@octokit/auth-action] The token variable is specified more than once. Use either `with.token`, `with.GITHUB_TOKEN`, or `env.GITHUB_TOKEN`.

### ISSUE THREAD

**Issue by milimyname** [ataylorme/eslint-annotate-action#76] opened 2024-02-26 10:03 UTC
Hi everyone!

Thank u for the action!

However, it fails now... I wonder whether it is something to do with the latest updates?

```yml
Run ataylorme/eslint-annotate-action@v3
  with:
    report-json: eslint_report.json
    markdown-report-on-step-summary: true
    GITHUB_TOKEN: ***
    only-pr-files: true
    fail-on-warning: false
    fail-on-error: true
    check-name: ESLint Report Analysis
  env:
    GITHUB_TOKEN: ***
/home/runner/work/_actions/ataylorme/eslint-annotate-action/v3/dist/index.js:[2](https://github.com/viadkt/energie-quartier/actions/runs/8046592630/job/21974115949#step:7:2)5[3](https://github.com/viadkt/energie-quartier/actions/runs/8046592630/job/21974115949#step:7:3)59
    throw new Error(
    ^

Error: [@octokit/auth-action] The token variable is specified more than once. Use either `with.token`, `with.GITHUB_TOKEN`, or `env.GITHUB_TOKEN`. See https://github.com/octokit/auth-action.js#createactionauth
    at createActionAuth2 (/home/runner/work/_actions/ataylorme/eslint-annotate-action/v3/dist/index.js:25359:11)
    at new Octokit (/home/runner/work/_actions/ataylorme/eslint-annotate-action/v3/dist/index.js:25595:20)
    at new OctokitWithDefaults (/home/runner/work/_actions/ataylorme/eslint-annotate-action/v3/dist/index.js:25510:11)
    at 90[4](https://github.com/viadkt/energie-quartier/actions/runs/8046592630/job/21974115949#step:7:4)2 (/home/runner/work/_actions/ataylorme/eslint-annotate-action/v3/dist/index.js:[5](https://github.com/viadkt/energie-quartier/actions/runs/8046592630/job/21974115949#step:7:5)[6](https://github.com/viadkt/energie-quartier/actions/runs/8046592630/job/21974115949#step:7:6)12[7](https://github.com/viadkt/energie-quartier/actions/runs/8046592630/job/21974115949#step:7:7):17)
    at __nccwpck_require__ (/home/runner/work/_actions/ataylorme/eslint-annotate-action/v3/dist/index.js:5[8](https://github.com/viadkt/energie-quartier/actions/runs/8046592630/job/21974115949#step:7:8)661:43)
    at 8481 (/home/runner/work/_actions/ataylorme/eslint-annotate-action/v3/dist/index.js:562[9](https://github.com/viadkt/energie-quartier/actions/runs/8046592630/job/21974115949#step:7:9)7:37)
    at __nccwpck_require__ (/home/runner/work/_actions/ataylorme/eslint-annotate-action/v3/dist/index.js:58661:43)
    at 6[14](https://github.com/viadkt/energie-quartier/actions/runs/8046592630/job/21974115949#step:7:15)4 (/home/runner/work/_actions/ataylorme/eslint-annotate-action/v3/dist/index.js:56540:45)
    at __nccwpck_require__ (/home/runner/work/_actions/ataylorme/eslint-annotate-action/v3/dist/index.js:58661:43)
    at /home/runner/work/_actions/ataylorme/eslint-annotate-action/v3/dist/index.js:58681:37

Node.js v[20](https://github.com/viadkt/energie-quartier/actions/runs/8046592630/job/21974115949#step:7:21).8.1

```

**Comment by neumayr** [comment] 2024-02-26 11:37
Our Team encountered the same issue and we think it might have been caused by a [commit on February 22nd in the `v3` branch](https://github.com/ataylorme/eslint-annotate-action/commits/v3/?since=2024-02-22&until=2024-02-23).

We then noticed that the `3.0.x` branch doesn't have any [official release](https://github.com/ataylorme/eslint-annotate-action/releases) tags yet. 🤔 

Hey @ataylorme, I hope you're doing well. Would you happen to know if `v3` is a work-in-progress branch or if it's considered stable? I would really appreciate your official recommendation.

Wanted to let you know that there are [100+](https://github.com/search?q=%22Bump+ataylorme%2Feslint-annotate-action+from+2+to+3%22+in%3Apullrequests&type=pullrequests) of Dependabot update pull requests available, suggest upgrading from `v2` to `v3`. Just thought you might want to check it out! We merged ours without investigating further until the error occurred, so I wanted to share our experience with you.

**Comment by ataylorme** [comment] 2024-02-26 13:34
Oh wow, yeah v3 branch is unstable and a work in progress. I’m not sure why Dependabot is making PRs when there isn’t a release. I’d recommend sticking with v2 for now. I’ll try to hurry up and get v3 finalized for a release. It will have breaking changes so just updating the referenced version won’t be enough

**Comment by neumayr** [comment] 2024-02-26 14:53
📖 https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management

The Docs suggest to name the branch with an `-beta` suffix. May this change will stop Dependabot create those Bump PRs.

**Comment by ataylorme** [comment] 2024-02-26 15:05
I renamed the branch to add -beta. I will remove it after tagging a 3.0.0 release.

I honestly had no idea how many people are using this action. I’m glad to see the number is high but also disappointed for the issue with the new version.

The marketplace continued to show 2.2.0 as the latest even with the v3 branch so I thought it was fine. I appreciate you making me aware.

**Comment by ataylorme** [comment] 2024-04-19 02:52
[`3.0.0` has been released](https://github.com/ataylorme/eslint-annotate-action/releases/tag/3.0.0). Please update any references to the `v3` branch instead of `v3-beta`. Make sure to read the Changeling as there are breaking changes (GH_TOKEN input has changed)

**Closed as completed by ataylorme** 2024-04-19 02:52 UTC

**Comment by motlin** [comment] 2025-08-09 03:45
I'm running into the same issue with 3.0.0. What is the fix? Do I have to specify `GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`? The docs say it is optional.

My GHA:
```
    eslint:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            checks: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v4
            - uses: jdx/mise-action@v2

            - run: just eslint-ci
              continue-on-error: true

            - uses: ataylorme/eslint-annotate-action@3.0.0
              if: always()
```

The error in GHA logs:

```
Run ataylorme/eslint-annotate-action@3.0.0
/home/runner/work/_actions/ataylorme/eslint-annotate-action/3.0.0/dist/index.js:25359
    throw new Error(
    ^

Error: [@octokit/auth-action] The token variable is specified more than once. Use either `with.token`, `with.GITHUB_TOKEN`, or `env.GITHUB_TOKEN`. See https://github.com/octokit/auth-action.js#createactionauth
```
