### ISSUE TITLE
GHE Bad Credentials 

### ISSUE THREAD

**Issue by cgatian** [ataylorme/eslint-annotate-action#48] opened 2022-09-23 14:45 UTC
On GHE 3.5 and experiencing the following error:

```
2022-09-23T13:58:22.6907309Z ℹ  info      1 ESLint error(s) and 1 ESLint warning(s) found
2022-09-23T13:58:22.8592709Z ✖  fatal     Bad credentials
```

Other GitHub Actions that take the GITHUB_TOKEN are working.  Perhaps the token lacks the specific permission the action needs? 

Here are my token permissions:

```
2022-09-23T13:55:08.3191335Z ##[group]GITHUB_TOKEN Permissions
2022-09-23T13:55:08.3192293Z Actions: write
2022-09-23T13:55:08.3192762Z Checks: write
2022-09-23T13:55:08.3193288Z Contents: write
2022-09-23T13:55:08.3193778Z Deployments: write
2022-09-23T13:55:08.3194267Z Discussions: write
2022-09-23T13:55:08.3194745Z Issues: write
2022-09-23T13:55:08.3195289Z Metadata: read
2022-09-23T13:55:08.3195736Z Packages: write
2022-09-23T13:55:08.3196206Z Pages: write
2022-09-23T13:55:08.3196689Z PullRequests: write
2022-09-23T13:55:08.3197236Z RepositoryProjects: write
2022-09-23T13:55:08.3197813Z SecurityEvents: write
2022-09-23T13:55:08.3198309Z Statuses: write
2022-09-23T13:55:08.3198779Z ##[endgroup]
```

Maybe it has something to do with setting `antiope` preview?  Looks like that's been merged into the official for some time now.

https://github.com/ataylorme/eslint-annotate-action/blob/v2/src/constants.ts#L18

**Comment by cgatian** [comment] 2022-09-23 15:09
According to [the Octokit docs](https://octokit.github.io/rest.js/v16#checks-create), `checks:write` is required. 🤷

**Comment by cgatian** [comment] 2022-09-23 15:10
Disabled `only-pr-files` and same results.

**Comment by ataylorme** [comment] 2023-01-22 00:01
I do think this is a permission error though I don't have anything on GitHub Enterprise to test.

Maybe there is [an enterprise setting/restriction](https://docs.github.com/en/enterprise-server@3.7/admin/policies/enforcing-policies-for-your-enterprise/enforcing-policies-for-github-actions-in-your-enterprise#enforcing-a-policy-for-workflow-permissions-in-your-enterprise) not allowing `checks:write` on `GITHUB_TOKEN`

I've seen a similar error when the action runs on pull requests from a fork and lack `write` permission

**Comment by ataylorme** [comment] 2024-04-19 02:55
@cgatian not sure if you are still interested in self-hosted GitHub Enterprise support. If so, [`3.0.0` has been released](https://github.com/ataylorme/eslint-annotate-action/releases/tag/3.0.0). I welcome pull requests to the `v3` branch if you want to try and add support.

**Comment by ataylorme** [comment] 2024-04-19 02:58
Closing as a duplicate of #69. Even though this PR came first that one has a more appropriate title in that GHE support would be a new feature

**Closed as completed by ataylorme** 2024-04-19 02:58 UTC
Labels: enhancement
